install.packages('devtools', repos='http://cran.us.r-project.org')
install.packages('RCurl', repos='http://cran.us.r-project.org')
library(devtools)
install_github('IRkernel/repr')
install_github('IRkernel/IRdisplay')
install_github('IRkernel/IRkernel')
IRkernel::installspec()
q()