#!/bin/sh
ln -s libcrsjniproj.so.0.1.1 libcrsjniproj.so
ln -s libcrsjniproj.so.0.1.1 libcrsjniproj.so.0
ln -s libcrypto.so.0.9.7 libcrypto.so
ln -s libcrypto.so.0.9.7 libcrypto.so.0
ln -s libgdal.so.1.12.2 libgdal.so
ln -s libgdal.so.1.12.2 libgdal.so.1
ln -s libgrass_datetime.6.0.2.so libgrass_datetime.so
ln -s libgrass_dbmibase.6.0.2.so libgrass_dbmibase.so
ln -s libgrass_dbmiclient.6.0.2.so libgrass_dbmiclient.so
ln -s libgrass_dgl.6.0.2.so libgrass_dgl.so
ln -s libgrass_dig2.6.0.2.so libgrass_dig2.so
ln -s libgrass_gis.6.0.2.so libgrass_gis.so
ln -s libgrass_gmath.6.0.2.so libgrass_gmath.so
ln -s libgrass_gproj.6.0.2.so libgrass_gproj.so
ln -s libgrass_I.6.0.2.so libgrass_I.so
ln -s libgrass_linkm.6.0.2.so libgrass_linkm.so
ln -s libgrass_rtree.6.0.2.so libgrass_rtree.so
ln -s libgrass_vask.6.0.2.so libgrass_vask.so
ln -s libgrass_vect.6.0.2.so libgrass_vect.so
ln -s libjasper-1.701.so.1 libjasper-1.701.so
ln -s libjasper-1.701.so.1 libjasper-1.701.so.1.0.0
ln -s libjecw.so.0.0.7 libjecw.so
ln -s libjecw.so.0.0.7 libjecw.so.0
ln -s libjecw.so.0.0.7 libjecw.so.0.0.1
ln -s libjgdal.so.0.9.2 libjgdal.so
ln -s libjgdal.so.0.9.2 libjgdal.so.0
ln -s libjmrsid.so.0.0.6 libjmrsid.so
ln -s libjmrsid.so.0.0.6 libjmrsid.so.0
ln -s libNCScnet.so libNCSCnet.so
ln -s libNCScnet.so libNCSCNet.so
ln -s libNCScnet.so libNCScnet.so.0
ln -s libNCScnet.so libNCSCnet.so.0
ln -s libNCScnet.so libNCSCNet.so.0 
ln -s libNCSEcw.so libNCSEcw.so.0 
ln -s libNCSEcwC.so libNCSEcwC.so.0
ln -s libNCSUtil.so libNCSUtil.so.0
ln -s libodbc.so.1 libodbc.so
ln -s libodbc.so.1 libodbc.so.1.0.0 
ln -s libpng.so.3 libpng.so
ln -s libpng.so.3 libpng.so.3.1.2.5
ln -s libpq.so.3 libpq.so
ln -s libproj.so.0.5.0 libproj.so
ln -s libproj.so.0.5.0 libproj.so.0
ln -s libssl.so.0.9.7 libssl.so
ln -s libssl.so.0.9.7 libssl.so.0
