#!/bin/bash

ATLASSTYLER_HOME=/usr/share/atlasstyler

cd $ATLASSTYLER_HOME

./start_AtlasStyler.sh ${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9} ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17}
# try, try again ..
if [ \$? -ne 0 ] ; then
   . ./start_AtlasStyler.sh                 
fi
